# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/prabin/git/BallStick

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/prabin/git/BallStick

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/prabin/git/BallStick/CMakeFiles /home/prabin/git/BallStick/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/prabin/git/BallStick/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ballnstick

# Build rule for target.
ballnstick: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ballnstick
.PHONY : ballnstick

# fast build rule for target.
ballnstick/fast:
	$(MAKE) -f CMakeFiles/ballnstick.dir/build.make CMakeFiles/ballnstick.dir/build
.PHONY : ballnstick/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named mouse

# Build rule for target.
mouse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mouse
.PHONY : mouse

# fast build rule for target.
mouse/fast:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/build
.PHONY : mouse/fast

src/ballnstick.o: src/ballnstick.cpp.o

.PHONY : src/ballnstick.o

# target to build an object file
src/ballnstick.cpp.o:
	$(MAKE) -f CMakeFiles/ballnstick.dir/build.make CMakeFiles/ballnstick.dir/src/ballnstick.cpp.o
.PHONY : src/ballnstick.cpp.o

src/ballnstick.i: src/ballnstick.cpp.i

.PHONY : src/ballnstick.i

# target to preprocess a source file
src/ballnstick.cpp.i:
	$(MAKE) -f CMakeFiles/ballnstick.dir/build.make CMakeFiles/ballnstick.dir/src/ballnstick.cpp.i
.PHONY : src/ballnstick.cpp.i

src/ballnstick.s: src/ballnstick.cpp.s

.PHONY : src/ballnstick.s

# target to generate assembly for a file
src/ballnstick.cpp.s:
	$(MAKE) -f CMakeFiles/ballnstick.dir/build.make CMakeFiles/ballnstick.dir/src/ballnstick.cpp.s
.PHONY : src/ballnstick.cpp.s

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/play_game.o: src/play_game.cpp.o

.PHONY : src/play_game.o

# target to build an object file
src/play_game.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/play_game.cpp.o
.PHONY : src/play_game.cpp.o

src/play_game.i: src/play_game.cpp.i

.PHONY : src/play_game.i

# target to preprocess a source file
src/play_game.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/play_game.cpp.i
.PHONY : src/play_game.cpp.i

src/play_game.s: src/play_game.cpp.s

.PHONY : src/play_game.s

# target to generate assembly for a file
src/play_game.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/play_game.cpp.s
.PHONY : src/play_game.cpp.s

src/x11_test.o: src/x11_test.cpp.o

.PHONY : src/x11_test.o

# target to build an object file
src/x11_test.cpp.o:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/x11_test.cpp.o
.PHONY : src/x11_test.cpp.o

src/x11_test.i: src/x11_test.cpp.i

.PHONY : src/x11_test.i

# target to preprocess a source file
src/x11_test.cpp.i:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/x11_test.cpp.i
.PHONY : src/x11_test.cpp.i

src/x11_test.s: src/x11_test.cpp.s

.PHONY : src/x11_test.s

# target to generate assembly for a file
src/x11_test.cpp.s:
	$(MAKE) -f CMakeFiles/mouse.dir/build.make CMakeFiles/mouse.dir/src/x11_test.cpp.s
.PHONY : src/x11_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ballnstick"
	@echo "... game"
	@echo "... mouse"
	@echo "... rebuild_cache"
	@echo "... src/ballnstick.o"
	@echo "... src/ballnstick.i"
	@echo "... src/ballnstick.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/play_game.o"
	@echo "... src/play_game.i"
	@echo "... src/play_game.s"
	@echo "... src/x11_test.o"
	@echo "... src/x11_test.i"
	@echo "... src/x11_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

